config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'pages#home'
  get 'privacy', to: 'pages#privacy', as: 'privacy'

  get 'team', to: 'pages#team', as: 'team'


  get 'roadmap', to: 'pages#road_map', as: 'road_map'
  get 'faq', to: 'pages#faq', as: 'faq'

  get 'login', to: 'pages#login', as: 'login'
  get 'ico', to: 'pages#ico', as: 'ico'
  get 'accredited_form', to: 'pages#accredited_form', as: 'accredited_form'
  get 'not_accredited', to: 'pages#not_accredited', as: 'not_accredited'
  post 'accredited_form_post', to: 'pages#accredited_form_post', as: 'accredited_form_post'

  get 'referrals', to: 'pages#referrals', as: 'referrals'
  get 'referral_link', to: 'pages#referral_link', as: 'referral_link'
  patch 'retrieve_referral_link', to: 'pages#retrieve_referral_link', as: 'retrieve_referral_link'

  get 'eth_address_form', to: 'pages#eth_address_form', as: 'eth_address_form'
  patch 'eth_address_form_submit', to: 'pages#eth_address_form_submit', as: 'eth_address_form_submit'

  get 'admin', to: 'pages#admin', as: 'admin'
  get 'email_csv', to: 'pages#email_csv'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
require 'csv'
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_secure_token :referral_id

  def valid_investor?
    return false unless terms_agreed?
    us_based? ? accredited? : true
  end

  def first_referred_login?
    referrer_id.present? && eth_address.nil? && update(eth_address: '')
  end

  class << self
    def email_csv
      CSV.generate(headers: true) do |csv|
        csv << %w{email}
        all.each do |user|
          csv << user.attributes.values_at(*%w{email})
        end
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  protected

  def after_sign_in_path_for(resource)
    ico_path
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, :only => [:ico]
  before_action :set_random_guests

  def home
  end

  def privacy
  end

  def road_map
  end

  def faq

  end

  def login
    render layout: 'blank'
  end

  def ico
    # (redirect_to accredited_form_path and return) unless current_user.valid_investor?
    (redirect_to accredited_form_path and return) unless current_user.terms_agreed?
    redirect_to eth_address_form_path if current_user.first_referred_login?
  end

  def accredited_form
  end

  def accredited_form_post
    us_based = params[:us_based] == 'yes'
    accredited = params[:accredited] == 'yes'
    terms = params[:terms] == 'yes'
    current_user.update(us_based: us_based, accredited: accredited, terms_agreed: terms, terms_agreed_at: Time.now)

    # unless current_user.valid_investor?
    unless current_user.terms_agreed?
      flash[:error] = '''
        All investors must accept the terms of service.<br/>
        At this time we are only able to offer the ICO to US based investors if they are accredited.<br/>
        We apologize for this inconvenience.
      '''

      redirect_to accredited_form_path and return
    end

    redirect_to ico_path
  end

  def referrals
    # (redirect_to ico_path and return) unless current_user.valid_investor?
  end

  def retrieve_referral_link
    current_user.update(eth_address: params[:user][:eth_address])
    redirect_to referral_link_path
  end

  def referral_link
  end

  def eth_address_form
  end

  def eth_address_form_submit
    current_user.update(eth_address: params[:user][:eth_address])
    redirect_to ico_path
  end

  def admin
    redirect_to ico_path unless current_user.admin?

    @user_info = User.pluck(:email, :sign_in_count, :last_sign_in_at)
  end

  def email_csv
    if current_user.admin?
      respond_to do |format|
        format.csv { send_data User.email_csv }
      end
    else
      head :forbidden
    end
  end

  def set_random_guests
    if session[:random_guests].nil?
      session[:random_guests] = rand(8..22)
      session[:guests_set_at] = Time.now
    elsif session[:guests_set_at].present?
      if Time.now > session[:guests_set_at].to_datetime + 30.minutes
        session[:random_guests] = rand(8..22)
        session[:guests_set_at] = Time.now
      end
    end
  end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  def new
    @referrer_id = params[:ref_id]
    super
  end

  private

  def sign_up_params
    params.require(:user).permit(:email, :password, :password_confirmation, :referrer_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_scripts.html.erb
<!-- start Mixpanel -->
<script type="text/javascript">(function(e,a){if(!a.__SV){var b=window;try{var c,l,i,j=b.location,g=j.hash;c=function(a,b){return(l=a.match(RegExp(b+"=([^&]*)")))?l[1]:null};g&&c(g,"state")&&(i=JSON.parse(decodeURIComponent(c(g,"state"))),"mpeditor"===i.action&&(b.sessionStorage.setItem("_mpcehash",g),history.replaceState(i.desiredHash||"",e.title,j.pathname+j.search)))}catch(m){}var k,h;window.mixpanel=a;a._i=[];a.init=function(b,c,f){function e(b,a){var c=a.split(".");2==c.length&&(b=b[c[0]],a=c[1]);b[a]=function(){b.push([a].concat(Array.prototype.slice.call(arguments,
0)))}}var d=a;"undefined"!==typeof f?d=a[f]=[]:f="mixpanel";d.people=d.people||[];d.toString=function(b){var a="mixpanel";"mixpanel"!==f&&(a+="."+f);b||(a+=" (stub)");return a};d.people.toString=function(){return d.toString(1)+".people (stub)"};k="disable time_event track track_pageview track_links track_forms register register_once alias unregister identify name_tag set_config reset opt_in_tracking opt_out_tracking has_opted_in_tracking has_opted_out_tracking clear_opt_in_out_tracking people.set people.set_once people.unset people.increment people.append people.union people.track_charge people.clear_charges people.delete_user".split(" ");
for(h=0;h<k.length;h++)e(d,k[h]);a._i.push([b,c,f])};a.__SV=1.2;b=e.createElement("script");b.type="text/javascript";b.async=!0;b.src="undefined"!==typeof MIXPANEL_CUSTOM_LIB_URL?MIXPANEL_CUSTOM_LIB_URL:"file:"===e.location.protocol&&"//cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js".match(/^\/\//)?"https://cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js":"//cdn4.mxpnl.com/libs/mixpanel-2-latest.min.js";c=e.getElementsByTagName("script")[0];c.parentNode.insertBefore(b,c)}})(document,window.mixpanel||[]);
mixpanel.init("ca6574c4d85d05e824f890dbe3c823c6");</script>
<!-- end Mixpanel -->

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-121922211-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-121922211-1');
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>VyB</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon" >

    <%= favicon_link_tag "vybLogo.png" %>
    <link href="https://fonts.googleapis.com/css?family=Raleway:300,400,600" rel="stylesheet">
    <link href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.4.0/Chart.min.js"></script>


    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <script src="https://unpkg.com/scrollreveal/dist/scrollreveal.min.js"></script>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
    <script>
      networkId = <%= ENV['network_id'] || 3 %>
    </script>

    <% if browser.chrome? %>
      <style type="text/css">
        body {
          font-family: 'Raleway', sans-serif;
        }
      </style>
    <% end %>

    <meta name="turbolinks-cache-control" content="no-cache">

    <%= render 'layouts/scripts' %>

  </head>

  <body class="<%= controller_name %> <%= action_name %>">
    <%= render "navigation/navbar" %>

    <div class="container-fluid main">
      <%= yield %>
    </div>

    <a href="mailto:info@myvyb.io" target="_blank" id='telegram-fab'><i class='fa fa-envelope fa-4x'></i> </a>

    <%= render "navigation/footer" %>
  </body>
</html>

app/views/layouts/blank.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>4NEW | Waste to Energy Blockchain Solution</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="icon">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class='blank'>
    <%= yield %>
  </body>
</html>

app/views/navigation/_footer.html.erb
<section id='footer' class='d-flex flex-column flex-md-row justify-content-around align-items-center align-items-md-start white-bg'>
  <div class='flex-column text-center'>
    <p>Find Us on Social Media</p>
    <div class='d-flex flex-row justify-content-center pb-2'>
      <a href="https://www.facebook.com/MyVyB" target='_blank' class='mr-4'><i class='ion-social-facebook royal-blue'></i></a>
      <a href="https://twitter.com/vyb_io" target='_blank' class='mr-4'><i class='ion-social-twitter royal-blue'></i></a>
      <a href="https://t.me/vybcoin" target='_blank' class='mr-4'><i class="mt-1 fa fa-telegram royal-blue"></i></i></a>
    </div>
    <div class='d-flex flex-row justify-content-center'>
      <a href="https://www.linkedin.com/company/myvyb/" target='_blank' class='mr-4'><i class='ion-social-linkedin royal-blue'></i></a><br>
      <a href="https://www.instagram.com/myvyb.io/" target='_blank' class='mr-4'><i class='ion-social-instagram royal-blue'></i></a><br>
    </div>
  </div>

  <!-- <div class='flex-column text-center'>
    <p>More Information</p>
  </div> -->

  <div class='flex-column text-center'>
    <p>Site Map</p>
    <span><%= link_to 'Home', root_path %></span><br>

    <span><%= link_to 'Newsletter', asset_path("https://fs27.formsite.com/jXj1Rk/form2/index.html
"), target: :_blank %></span><br>

    <span><%= link_to 'For Investors', asset_path("vyb_trifold_final.pdf"), target: :_blank %></span><br>

  </div>

  <div class='flex-column text-center'>
    <a class="navbar-brand" href="/"><%= image_tag 'vybLogo.png', class: 'black_circle_logo' %></a><br>
    <span><%= mail_to 'info@myVyB.io' %></span><br>
  </div>
</section>
<section class='d-flex pb-2 flex-row justify-content-center black-bg'>
  <span class='white'><small>©VyB 2018. All rights reserved.</small></span>
</section>

app/views/navigation/_navbar.html.erb
<nav class="navbar navbar-expand-lg fixed-top navbar-dark pl-5 pr-5">
  <a class="navbar-brand " href="/">
    <%= image_tag 'vybLogo.png', class: 'white_circle_logo' %>
    <div class='logo_text d-flex flex-column justify-content-center'>
      <span class='d-flex flex-row justify-content-start'>
      <br>
      <!--<span class='purple thick-text logo_name'> </span>-->
         <!--<span class='white thick-text logo_name'></span>-->
      </span>
      <span class='faded-blue logo_tagline'>by VyB Technologies, LLC.</span>
    </div>
  </a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

<div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <%= link_to 'For Investors', asset_path("vyb_trifold_final.pdf"), target: :_blank, class: 'nav-link btn turquoise-btn' %>
      </li>

      <li class="nav-item">
        <%= link_to 'The Team', "#meetTheTeam" , class: 'nav-link btn turquoise-btn' %>
      </li>

      <li class="nav-item">
        <%= link_to 'Join Newsletter!', asset_path("https://fs27.formsite.com/jXj1Rk/form2/index.html
"), target: :_blank, class: 'nav-link btn turquoise-btn' %>
      </li>
    </ul>
  </div>

</nav>

app/views/pages/_eth_address_form.html.erb
<div class="alert alert-danger" role="alert" style="display: none">
  Invalid ETH address!
</div>
<div>
  <%= form_for current_user, url: path do |f| %>
    <%= f.label('Ethereum Address:') %>
    <%= f.text_field :eth_address, class: 'form-control' %>
    <br/>
    <%= f.submit 'Save address', class: 'btn turquoise-btn', data: { disable_with: false } %>
  <% end %>
</div>

app/views/pages/_featured_in.html.erb
<section class='featured-section pl-5 pr-5'>
  <h5 class='title white'>Featured On</h5>
  <div class='d-flex flex-wrap flex-row justify-content-around align-items-center'>

    <a href="http://6abc.com/technology/" target='_blank' class='partner'>
      <%= image_tag 'abc.png', class: ' reduce' %>
    </a>
    
    <a href="http://cbs.com/" target='_blank' class='partner'>
      <%= image_tag 'cbs.png', class: 'small-size' %>
    </a>

    <a href="https://mashable.com/" target='_blank' class='partner'>
      <%= image_tag 'mashable.png', class: 'small-size' %>
    </a>

    <a href="http://people.com/" target='_blank' class='partner'>
      <%= image_tag 'people.png', class: 'small-size' %>
    </a>

    <a href="http://jennacommunications.com/" target='_blank' class='partner'>
      <%= image_tag 'fox29.png', class: 'small-size translucent' %>
    </a>

  </div>
</section>

app/views/pages/_features.html.erb
<section class='features-section'>
  <div class="title-bar features">
    <h3 class='title white m-0'>Features</h3>
  </div>
  <section class='features-box'>
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-6">
        <div class="blue-card reveal-card-left">
          <div class="icon-box">
          </div>
          <h5 class='ultra-turquoise'>Easy Transparency</h5>
          <p>For the first time, users will be able to see how they are truly viewed. VyB will create a seamless profile and experience over social media, and in real interactions. Utilizing the Blockchain, VyB scores will not only be transparent, they will be decentralized amongst all users and immutable mitigating possible corruption.</p>
        </div>
      </div>
      <div class="col-sm-12 col-md-12 col-lg-6">
        <div class="blue-card reveal-card-right">
          <div class="icon-box">
          </div>
          <h5 class='ultra-turquoise'>Simple and Efficient</h5>
          <p>The VyB score, a score out of '5.00' will be simple and efficient. While the algorithms creating the score are complex and mathematically sophisticated, the entire world will be able to understand the difference between a lower and a higher score. As such, VyB will be able to help create a universal metric that any individual can understand.</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-sm-12 col-md-12 col-lg-6">
        <div class="blue-card reveal-card-left">
          <div class="icon-box">
          </div>
          <h5 class='ultra-turquoise'>Easy to Integrate</h5>
          <p>We live in a world that asks feedback all around us. Whether at the end of an Uber ride or sometimes during dinner at a restaurant - service providers are seeking feedback. VyB will be efficiently integrated in existing workflows to create a single source of truth for feedback. One's VyB score will visible on social media, dating sites, and more!</p>
        </div>
      </div>
      <div class="col-sm-12 col-md-12 col-lg-6">
        <div class="blue-card reveal-card-right">
          <div class="icon-box">
          </div>
          <h5 class='ultra-turquoise'>VyB for Business</h5>
          <p>VyB will be able to be used in the workplace and will substitute the "Performance Reviews" that many employers seek. VyB for Business will revolutionize how feedback is conveyed in the workplace, ultimately increasing performance, productivity and the organizational growth. Every employer wants to hire credible employees, and VyB is the solution.</p>
        </div>
      </div>
    </div>


  </section>

</section>

app/views/pages/_opt_ins.html.erb
<section class='content white-bg'>
  <div class='row justify-content-center'>
    <div class='d-flex justify-content-start justify-sm-content-around'>
      <%= link_to 'Join Newsletter', "https://fs27.formsite.com/jXj1Rk/form2/index.html", class: 'join-ico btn turquoise-btn mr-3 btn-lg' %>
      <%= link_to 'Follow us on Instagram', "https://www.instagram.com/myvyb.io/", target: :_blank, class: 'd-none d-sm-block telegram btn royal-blue-btn btn-lg' %>
    </div>
  </div>
</section>

app/views/pages/_pricing.html.erb
<section class='roadmap-section'>
  <div class="title-bar roadmap">
    <h3 class='title white m-0'>Pricing</h3>
  </div>
  <section class='roadmap'>
    <ul class="timeline no-style break-containment">
      <li class="event">
        <h3>Private Sale</h3>
        <p>
          <ul>
            <li>
              <span class='thick-text'>1 ETH = 10,000 MANE</span>
            </li>

            <li>
              <span>Ends May 2nd, 2018</span>
            </li>

          </ul>
        </p>
      </li>
      <li class="event">
        <h3>ICO Presale</h3>
        <p>
          <ul>
            <li>
              <span class='thick-text'>1 ETH = 5,000 MANE</span>
            </li>
          </ul>
        </p>
      </li>

      <li class="event">
        <h3>ICO Phase 1</h3>
        <p>
          <ul>
            <li>
              <span class='thick-text'>1 ETH = 3,300 MANE</span>
            </li>
          </ul>
        </p>
      </li>

      <li class="event">
        <h3>ICO Phase 2</h3>
        <p>
          <ul>
            <li>
              <span class='thick-text'>1 ETH = 2,500 MANE</span>
            </li>
          </ul>
        </p>
      </li>

      <li class="event">
        <h3>ICO Phase 3</h3>
        <p>
          <ul>
            <li>
              <span class='thick-text'>1 ETH = 2,000 MANE</span>
            </li>
          </ul>
        </p>
      </li>
    </ul>
  </section>
</section>

app/views/pages/accredited_form.html.erb
<% provide(:ico, "active") %>

<section class="blog-post text-center">
  <div class="card card-body">
    <% if flash[:error].present? %>
      <div class="alert alert-danger" role="alert">
        <%= flash[:error].html_safe %>
      </div>
    <% end %>

    <%= form_tag accredited_form_post_path do %>

      <p>Do you agree to the <%= link_to 'terms of service', privacy_path, target: '_blank' %>?</p>
      <%= radio_button_tag(:terms, "yes") %>
      <%= label_tag(:terms_yes, "Yes") %>
      <%= radio_button_tag(:terms, "no") %>
      <%= label_tag(:terms_no, "No") %>
      <br/>

      <%= submit_tag 'Continue', class: 'btn btn-primary mt-2' %>
    <% end %>
  </div>

</section>

app/views/pages/admin.html.erb
<% provide(:ico, "active") %>

<section class="blog-post">
  <table id="user-info-table" class="table table-hover">
    <thead>
      <tr>
        <td>Email</td>
        <td>Sign in count</td>
        <td>Last sign in</td>
      </tr>
    </thead>
    <tbody>
      <% @user_info.each do |user| %>
        <tr>
          <td><%= user[0] %></td>
          <td><%= user[1] %></td>
          <td><%= user[2] %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>
<%= button_to "Download Emails as CSV", email_csv_path(:format => "csv"), method: :get %>

app/views/pages/eth_address_form.erb
<% provide(:ico, "active") %>

<section class="blog-post">
  <h3>Please enter the ETH address you will use to buy MANE coins.</h3>
  <%= render 'eth_address_form', path: eth_address_form_submit_path %>
</section>

app/views/pages/faq.html.erb
<section class='blog-post'>
	<h3 class='text-uppercase'>FAQ</h3>
	<br>
  <%= render 'faq' %>
</section>

app/views/pages/home.html.erb
<% provide(:home, "active") %>

<div id="home"></div>
<section class="jumbotron jumbotron-fluid m-0  d-flex flex-column flex-lg-row justify-content-between align-items-center">

  <%= video_tag "VybMovie.mp4", id: 'headline-video', class: 'headline-video', autoplay: false, loop: "loop", muted: true %>

  <div class='headline-image' style='background-image: url(<%= image_url 'vyb.png' %>)'></div>

  <div class='header main-headline reveal-jumbotron'>

    <h1 class='mb-2'><b>What's Your VyB?</b></h1>
    <h2 class='tagline mb-4'>VyB brings <u>transparency</u> and <u>accountability</u> into the world.</h2>

    <!-- Buttons -->
    <div class='d-flex justify-content-start justify-sm-content-around'>

      <a href="#whatIsVyb"><p class='join-ico btn turquoise-btn mr-3'>Learn More</p></a>

      <a href="https://fs27.formsite.com/jXj1Rk/form2/index.html
" target="_blank"><p class='d-none d-sm-block telegram btn transparent-btn'>Join the Newsletter</p></a>

    </div>

    <!-- Social media icon links -->
    <div class='d-flex mt-4 social-media-links'>
      <a href="https://www.facebook.com/MyVyB" target='_blank'><i class='ion-social-facebook royal-blue'></i></a>
      <a href="https://twitter.com/vyb_io" target='_blank'><i class='ion-social-twitter royal-blue'></i></a>
      <a href="https://www.linkedin.com/company/myvyb/" target='_blank'><i class='ion-social-linkedin royal-blue'></i></a>
      <a href="https://www.instagram.com/myvyb.io/" target='_blank'><i class='ion-social-instagram royal-blue'></i></a>

    </div>
  </div>
</section>

<%= render 'featured_in' %>

<%= render 'explainer' %>

<%= render 'disrupting_feedback_industry' %>

<div id="whatIsVyb">
  <%= render 'what_is_vyb' %>
</div>

<%= render 'features' %>

<%= render 'opt_ins' %>

<div id="meetTheTeam">
  <%= render 'team' %>
</div>

<%= render 'crypto_information' %>

<%= render 'opt_ins' %>

app/views/pages/ico.html.erb
<% provide(:page_title, "Dashboard") %>

<div id="ico"></div>
<div class="p-5 mb-4">
</div>
<div class="row">
	<div class="col-lg-4">
		<!--<div class="card electric-purple-bg mb-3">
			<div class="card-body">
				<h4 class='text-uppercase thin-text faded-blue'>Private Sale</h4>
				<p class='white'>44/200 Spots remaining</p>
				<div class="progress">
				  <div class="progress-bar faded-blue-bg" role="progressbar" style="width: 78%" aria-valuenow="78" aria-valuemin="0" aria-valuemax="100"></div>
				</div>
			</div>
			<div class="card-body dark-blue-bg">
				<span class='faded-blue'><%= session[:random_guests] %> people here now</span>
			</div>
		</div> -->

		<div class='card shadow-1 mb-4'>
			<div class="card-body pt-2 pb-3">
				<span class="badge badge-primary faded-blue-bg pt-1 pb-1 pl-3 pr-3">Private Sale</span>
				<h4 class='thick-text dark-blue mt-3'>1 ETH = 10,000 MANE</h4>
				<p class='dark-blue'>
					<span class='text-uppercase'>Ends On</span><br>
					<span class='thick-text'>May 2nd, 2018</span>
				</p>
			</div>
			<div class="card-body light-gray-bg">
				<p class='dark-blue'>
					<span class='text-uppercase'>Up Next: ICO Presale</span><br>
					<span class='thick-text'>Price will be: 1ETH = 5,000 MANE</span>
				</p>
			</div>
			<div class='card-body electric-purple-bg countdown'>
	      <span class='hours eco-green d-flex justify-content-between'>
	        <div class='days amount'></div>
	        <div class='divider'>:</div>
	        <div class='hours amount'></div>
	        <div class='divider'>:</div>
	        <div class='minutes amount'></div>
	        <div class='divider'>:</div>
	        <div class='seconds amount'></div>
	      </span>
	      <span class='title royal-blue text-uppercase d-flex justify-content-between'>
	        <div>days</div>
	        <div>hrs</div>
	        <div>min</div>
	        <div>sec</div>
	      </span>
	    </div>
		</div>

		<!-- <div class="card dark-blue-bg mb-3">
			<div class="card-body">
				<h4 class='text-uppercase thin-text faded-blue'>Referrals</h4>
				<% if current_user.eth_address.present? %>
					<p class='white'>Referrals are set up!</p>
					<%= link_to "Referral Link", referral_link_path, class: 'btn turquoise-btn btn-block' %>
				<% else %>
					<p class='white'>Tell your friends about ManeCoin and earn bonus tokens!</p>
					<%= link_to "Referrals", referrals_path, class: 'btn turquoise-btn btn-block' %>
				<% end %>
			</div>
		</div> -->
	</div>

	<div class='col-lg-8 justify-content-center'>
  	<div class='card shadow-1 mb-4'>
  		<div class='card-body'>
				<h5 class='thin-text'>Step 1</h5>

				<h4 class='mb-4'>Buy ManeCoin via ETH</h4>

        <div id='ETH'>
          <div class="alert alert-eco-green-border pt-4 d-flex justify-content-start align-items-center" role="alert">

            <div>
              <p><b>
								MANE Crowdsale Address
								<!-- <a class="crowdsale-etherscan" href="" target="_blank" >(Verified, Source)</a> -->
							</b></p>
              <p class='monospace crowdsale-address'>0x6de126fe427b7556328038a400afa99b857760b7</p>

            </div>

          </div>
          <ol>
            <li>Using your <a href='https://themerkle.com/top-5-ethereum-wallets-compatible-with-cryptocurrency-ico-tokens/' target='_blank'>compatible wallet</a>, send ETH to the above MANE Crowdsale Address.</li>
            <li>Wait for transaction verification.</li>
          </ol>
        </div>

			</div>
		</div>

		<div class='card shadow-1 mb-4'>
  		<div class='card-body'>
				<h5 class='thin-text'>Step 2</h5>
				<h4 class='mb-4'>Add the token to your wallet</h4>
  			<p><small>In your prefered Ethereum wallet, add the following token address:</small></p>

        <div class="alert alert-eco-green-border pt-4 d-flex justify-content-start align-items-center" role="alert">

          <div>
            <p><b>
							MANE Coin Address <a class="token-etherscan" href="" target="_blank">(Verified, Source)</a>
						</b></p>
            <p class='monospace token-address'>0xc20fa8213f9055e213ac2bd5d88d450590cc8540</p>
          </div>
        </div>
				<p>
					<b>Step-by-step guide for MyEtherWallet:</b>
				</p>
        <ol>
          <li>
            Click on “Add Custom Token” in the bottom right section of "Token Balances"
          </li>
          <li>
						Address: Copy and paste the above MANE Coin address
					</li>
          <li>
						Token Symbol: MANE
					</li>
          <li>
						Decimals: 18
					</li>
          <li>
						On pressing the "Save" button, you should see your MANE balance updated
					</li>
        </ol>
      </div>
		</div>

	</div>

</div>